### ISSUE TITLE
Support for Storybook v7

### ISSUE THREAD

**Issue by Corvimia** [josiahayres/storybook-addon-mantine#6]
Your addon looks great, but I wish I could use it with the latest version of storybook. Is that something I can expect soon?

Thank you

**Comment by josiahayres** [comment]
Hi @Corvimia yes! 
I've been investigating rebuilding the entire addon from scratch using Typescript. Currently on track to publish a new version that supports storybook v7 in the next week or so.

**Comment by josiahayres** [comment]
I have released version 2 this morning that works with latest storybook. Try `npm install storybook-addon-mantine@latest` to get the newest version in your project!
